engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      config:
        extensions:
          - .es6
          - .js
  method-lines:
    enabled: false
  eslint:
    enabled: true
    config:
      config_file: .eslintrc.json
  fixme:
    enabled: true
  file-lines:
   enabled: true
  identical-code:
   enabled: true
ratings:
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
  - "client/**/*.jsx"
exclude_paths:
  - "node_modules/"
  - "template/*"
  - "server/test"
  - "server/migrations/"
  - "server/models/"
  - "server/validators"
  - "server/reply/"
  - "**/test/*.js"
  - "**/*.test.js"
  - "__mocks__"
  - "client/src/actions/"
