engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      config:
        extensions:
          - .es6
          - .js
  method-lines:
    enabled: false
  eslint:
    enabled: true
    config:
      config_file: .eslintrc.json
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
  file-lines:
   enabled: false
  identical-code:
   enabled: false
ratings:
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
  - "client/**/*.jsx"
exclude_paths:
  - "node_modules/"
  - "template/*"
  - "server/test"
  - "server/migrations/"
  - "server/models/"
  - "server/validators"
  - "server/reply/"
  - "**/test/*.js"
  - "**/*.test.js"
  - "__mocks__"
