language: node_js

node_js: "6.11.4"

install:
- npm install

script:
- npm run test:travis

env:
- NODE_ENV=test

cache:
  directories:
  - "node_modules"

services:
- postgresql

before_script:
- createuser more-recipe -s -U postgres
- createdb moreRecipesTest --username=postgres
- sequelize db:migrate

notifications:
  webhooks: https://coveralls.io/webhook repo_token=IE0ObAuB2eSIWueuvaem8oevz4yYtTc59

after_success: npm run coverage
