export const USER = 'USER';
export const LOGIN_OR_REG_SUCCESS = 'LOGIN_OR_REG_SUCCESS';
export const RECIPE = 'RECIPE';

export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_FAV_RECIPES = 'GET_FAV_RECIPES';
export const GET_MY_RECIPES = 'GET_MY_RECIPES';
export const GET_TOP_RECIPES = 'GET_TOP_RECIPES';
export const GET_RECIPE = 'GET_MY_RECIPE';

export const BEGIN_AJAX_REQUEST = 'BEGIN_AJAX_REQUEST';
export const END_AJAX_REQUEST = 'END_AJAX_REQUEST';
export const AJAX_REQUEST_ERROR = 'AJAX_REQUEST_ERROR';
export const AJAX_REQUEST_AUTH_ERROR = 'AJAX_REQUEST_AUTH_ERROR';
export const AJAX_REQUEST_SUCCESS = 'AJAX_REQUEST_SUCCESS';

export const UPDATE_INGREDIENTS = 'UPDATE_INGREDIENTS';
export const UPDATE_DIRECTIONS = 'UPDATE_DIRECTIONS';
export const UPDATE_NAME_CATEGORY = 'UPDATE_NAME_CATEGORY';
export const UPDATE_ALL_RECIPE_FIELD = 'UPDATE_ALL_RECIPE_FIELD';

export const REDIRECT = 'REDIRECT';
export const REDIRECT_URL = 'REDIRECT_URL';
